[theme]
name = "gruvbox-ish"

[theme.base]
white = "#ebdbb2"
black = "#1d2021"
grey = "#7c6f64"
blue = "#83a598"
red = "#fb4934"
yellow = "#fabd2f"
orange = "#fe8019"
green = "#b8bb26"
purple = "#b16286"
cyan = "#689d6a"
magenta = "#b16286"

[theme.syntax]
attribute = "$yellow"
builtinType = "$orange"
comment = "$grey"
constant = "$purple"
constructor = "$blue"
embedded = "$cyan"
enum = "$green"
enum-member = "$yellow"
enumMember = "$yellow"
escape = "$cyan"
field = "$yellow"
function = "$blue"
"function.method" = "$blue"
interface = "$yellow"
keyword = "$purple"
method = "$blue"
number = "$purple"
property = "$yellow"
selfKeyword = "$purple"
string = "$green"
struct = "$yellow"
structure = "$yellow"
type = "$red"
"type.builtin" = "$orange"
typeAlias = "$yellow"
"variable.other.member" = "$orange"

[theme.ui]
"activity.background" = "$black"
"activity.current" = "$black"
"completion.background" = "$black"
"completion.current" = "#2C313A"
"editor.background" = "$black"
"editor.caret" = "$cyan"
"editor.current_line" = "#282828"
"editor.dim" = "#504945"
"editor.focus" = "#CCCCCC"
"editor.foreground" = "$white"
"editor.link" = "$cyan"
"editor.selection" = "$grey"
"hover.background" = "$black"
"lapce.active_tab" = "$black"
"lapce.border" = "#000000"
"lapce.dropdown_shadow" = "#000000"
"lapce.error" = "$red"
"lapce.inactive_tab" = "$grey"
"lapce.scroll_bar" = "$grey"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#898989"
"palette.background" = "$black"
"palette.current" = "#2C313A"
"panel.background" = "$black"
"panel.current" = "#2C313A"
"panel.hovered" = "#343A45"
"source_control.added" = "#b8bb2632"
"source_control.modified" = "#fabd2f32"
"source_control.removed" = "#fb493432"
"status.background" = "#000000"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "$grey"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#fbf1c7"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0
